### ISSUE TITLE
Add metadata to OBFL that will flow through the framework to PEF

### ISSUE THREAD

**Issue by kalaspuffar** [mtmse/dotify.formatter.impl#25]
Hi @bertfrees and @PaulRambags

### Feature request.

*Short description of the feature*
We enable the possibility to specify metadata tags with arbitrary attributes that will be kept during the processing and outputted on the first row of the output block.

https://github.com/mtmse/obfl/pull/19
https://github.com/mtmse/pef/pull/2
https://github.com/mtmse/dotify.api/pull/11
https://github.com/mtmse/dotify.formatter.impl/pull/24

*Use cases*
Adding a ```<metadata my-special-data="value" />``` in OBFL that will also be present in the PEF output.

**Comment by bertfrees** [comment]
I think I remember the context in which I had been thinking about this feature. I explained it here: https://github.com/daisy/pipeline-mod-braille/issues/201. @kalaspuffar If you want I can make a test for this use case.

**Comment by kalaspuffar** [comment]
Hi @bertfrees 

If you want that would be a great help. Seems like we are thinking about similar use-cases but if you have a different implementation in mind I'm all ears.

Best regards
Daniel

**Comment by bertfrees** [comment]
Different use case, but implementation is pretty much what I had in mind. There are not many options.

**Comment by bertfrees** [comment]
It just occurred to me that for my use case it would not be enough to attach the synchronization data to the rows. I need to know the exact positions in the text. An example to illustrate:

```xml
<obfl xmlns="http://www.daisy.org/ns/2011/obfl"
      xmlns:dp="http://www.daisy.org/ns/pipeline/pef-cross-refs#">
    <table-of-contents>
        <toc-block>
            <toc-entry ref-id="x">
                some text
                <bookmark dp:type="ref-start" dp:ref-id="x"/>
                <page-number ref-id="x"/>
                <bookmark dp:type="ref-end" dp:ref-id="x"/>
            </toc-entry>
        </toc-block>
    </table-of-contents>
    <sequence>
        <block id="x">
            <bookmark dp:type="target" dp:id="x"/>
            some text
        </block>
    </sequence>
</obfl>
```

The idea is to create a hyperlink from the `page-number` and let it point to the page in the book with that page number (or rather the place of the referenced block). So I need to know exactly where in the text the page number begins and ends.

This doesn't need to affect your implementation (https://github.com/mtmse/dotify.formatter.impl/pull/24), nor does it need to affect PEF (https://github.com/mtmse/pef/pull/2). If I ever decide to implement this I can just improve the code. However I think it should already be supported by the API (https://github.com/mtmse/dotify.api/pull/11). [`PagedMediaWriter`](https://mtmse.github.io/dotify.api/5.0.3/javadoc/org/daisy/dotify/api/writer/PagedMediaWriter.html) should allow you to insert characters or special objects into a row.

**Comment by bertfrees** [comment]
Shouldn't this be closed?
