### ISSUE TITLE
OSGi metadata broken

### ISSUE THREAD

**Issue by bertfrees** [mtmse/dotify.formatter.impl#26]
The last (snapshot) version has some missing OSGi metadata. It used to be like as follows:

```
Import-Package: org.daisy.dotify.api.engine;version="[5.0,5.1)",org.da
 isy.dotify.api.formatter;version="[5.0,5.1)",org.daisy.dotify.api.obf
 l;version="[5.0,5.1)",org.daisy.dotify.api.writer;version="[5.0,5.1)"
 ,org.daisy.streamline.api.tasks;version="[1.2,1.3)",javax.xml.namespa
 ce,javax.xml.parsers,javax.xml.stream,javax.xml.stream.events,javax.x
 ml.transform,javax.xml.transform.dom,javax.xml.transform.stream,javax
 .xml.xpath,net.sf.saxon;version="[9.5,10)",org.daisy.dotify.api.text;
 version="[5.0,6)",org.daisy.dotify.api.translator;version="[5.0,6)",o
 rg.daisy.dotify.common.io;version="[4.4,5)",org.daisy.dotify.common.s
 plitter;version="[4.4,5)",org.daisy.dotify.common.text;version="[4.4,
 5)",org.daisy.streamline.api.media;version="[1.3,2)",org.daisy.stream
 line.api.option;version="[1.4,2)",org.daisy.streamline.api.validity;v
 ersion="[1.3,2)",org.w3c.dom,org.xml.sax
```

Now it is:

```
Import-Package: org.daisy.dotify.api.engine;version="[5.0,5.1)",org.da
 isy.dotify.api.formatter;version="[5.0,5.1)",org.daisy.dotify.api.obf
 l;version="[5.0,5.1)",org.daisy.dotify.api.writer;version="[5.0,5.1)"
```

but the "javax.xml" packages are still used.

I think it has to do with commit 35590dc2d719395545dfd964549857956d7eacc2 where you deleted the task code.

**Comment by kalaspuffar** [comment]
Hi @bertfrees 

I see how this changes the OSGi package import reference. Not sure how to fix this, though, but I think we can still do that without adding packages from the streamline API interface as the pipeline does not use it. 

If you have any suggestions or know how to rectify the problem, I would appreciate any input. I haven't worked much with OSGi, so if I should fix this issue, I need to do some research.

Best regards
Daniel

**Comment by bertfrees** [comment]
I also don't immediately know how to fix it as I don't know what Joel is using to add the metadata. I'm also not very experienced with Gradle. But I'll help you. It's a pretty important issue for Pipeline. As a fallback solution I can probably make the package visible by doing something in the configuration of the OSGi framework, but that's not preferred.

**Comment by bertfrees** [comment]
Fixed by https://github.com/mtmse/dotify.formatter.impl/pull/27
